### ISSUE TITLE
Cannot Configure device oneino

### ISSUE THREAD

**Issue by GerryGit** [flatlander01/oneino#1]
I am experiencing a problem setting up oneino.
I can connect via my mobile, and the chipID password is accepted.
Terminal indicates:

Oneino initializing                                                           
Checking boot mode                                                            
No Config Found. initializing....                                             
192.168.4.1
   
If I access 192.168.4.1 I get the message "Please Configure the device to access control."

I assume I should see a config page asking for network credentials, but this does not happen.
Should I be changing some configuration in the code?
I have looked, but do not see any place to do this.

Thanks for your assistance.

**Comment by outofbit** [comment]
192.168.4.1/root
